-- Run once in the Supabase SQL editor: hard-delete a user and everything hanging off them.
--
-- Suspending (users.is_active = false) was the only way to get rid of someone. This is the
-- irreversible version, and it is deliberately one plpgsql function rather than twenty
-- .delete() calls from Python: a partial teardown -- cases gone, invoices left pointing at
-- nothing -- is far worse than no teardown, and only a single transaction rules that out.
--
-- p_dry_run = true computes the same counts and takes the same decisions but deletes
-- nothing, so the confirmation dialog is generated by the code that does the work and
-- cannot drift from it.
--
-- What "cascade" means here, exactly:
--   * A CLIENT owns cases, so their cases go, and with them every hearing, meeting,
--     invoice, payment, document, note, timeline entry and conveyancing matter attached.
--   * A LAWYER does not own cases -- their client does. Deleting a lawyer removes their
--     assignments, notes, client requests and conversations, and leaves other people's
--     cases standing.
--   * Rows that merely record the user as the ACTOR on something that survives
--     (documents.uploaded_by, case_timeline.created_by, ...) keep the record and lose the
--     attribution. Deleting those would destroy a third party's case history, which is
--     not this user's data to take with them.
--
-- The Supabase Auth account is NOT touched -- nothing links a users row to it but the
-- email. That login survives and starts failing at get_current_profile() with "No LexFlow
-- profile for this account"; remove it from the Auth dashboard if you want it gone.
--
-- Storage objects live outside Postgres, so the function returns the paths it orphaned
-- and app/controllers/users.py removes them from the bucket afterwards.

-- Attribution columns must be nullable for the "survives, loses attribution" rule above.
alter table documents             alter column uploaded_by  drop not null;
alter table case_timeline         alter column created_by   drop not null;
alter table case_status_history   alter column changed_by   drop not null;
alter table meetings              alter column conducted_by drop not null;
alter table matter_documents      alter column verified_by  drop not null;
alter table miscellaneous_expenses alter column created_by  drop not null;
alter table due_diligence         alter column lawyer_id    drop not null;

create or replace function delete_user_cascade(p_user_id bigint, p_dry_run boolean default true)
returns jsonb
language plpgsql
as $$
declare
  v_lawyer_id  bigint;
  v_client_id  bigint;
  v_case_ids   bigint[];
  v_matter_ids bigint[];
  v_doc_ids    bigint[];
  v_conv_ids   bigint[];
  v_paths      text[];
  v_result     jsonb;
begin
  if not exists (select 1 from users where user_id = p_user_id) then
    raise exception 'User % does not exist', p_user_id;
  end if;

  select lawyer_id into v_lawyer_id from lawyers where user_id = p_user_id;
  select client_id into v_client_id from clients where user_id = p_user_id;

  -- Only a client's cases are the client's to take. A lawyer's are not.
  select coalesce(array_agg(case_id), '{}') into v_case_ids
    from cases where v_client_id is not null and client_id = v_client_id;

  select coalesce(array_agg(matter_id), '{}') into v_matter_ids
    from conveyancing_matters where case_id = any(v_case_ids);

  select coalesce(array_agg(document_id), '{}') into v_doc_ids
    from documents where case_id = any(v_case_ids);

  select coalesce(array_agg(id), '{}') into v_conv_ids
    from conversations
   where (v_client_id is not null and client_id = v_client_id)
      or (v_lawyer_id is not null and lawyer_id = v_lawyer_id);

  -- Every stored object about to lose its row, for the caller to remove from the bucket.
  select coalesce(array_agg(path), '{}') into v_paths from (
    select file_path as path from documents where document_id = any(v_doc_ids) and file_path is not null
    union all
    select attachment_path from messages where conversation_id = any(v_conv_ids) and attachment_path is not null
  ) p;

  v_result := jsonb_build_object(
    'user_id', p_user_id,
    'is_lawyer', v_lawyer_id is not null,
    'is_client', v_client_id is not null,
    'cases', coalesce(array_length(v_case_ids, 1), 0),
    'matters', coalesce(array_length(v_matter_ids, 1), 0),
    'documents', coalesce(array_length(v_doc_ids, 1), 0),
    'conversations', coalesce(array_length(v_conv_ids, 1), 0),
    'invoices', (select count(*) from invoices where case_id = any(v_case_ids)),
    'hearings', (select count(*) from hearings where case_id = any(v_case_ids)),
    'meetings', (select count(*) from meetings where case_id = any(v_case_ids)),
    'notifications', (select count(*) from notifications where user_id = p_user_id or case_id = any(v_case_ids)),
    'case_assignments', (select count(*) from case_lawyers where v_lawyer_id is not null and lawyer_id = v_lawyer_id),
    'storage_paths', to_jsonb(v_paths)
  );

  if p_dry_run then
    return v_result || jsonb_build_object('dry_run', true);
  end if;

  -- Children first, all the way down: anything that would be left pointing at a deleted
  -- parent has to go before that parent does.
  delete from ai_summaries where document_id = any(v_doc_ids);
  delete from matter_documents where matter_id = any(v_matter_ids) or document_id = any(v_doc_ids);
  delete from documents where document_id = any(v_doc_ids);

  delete from payments where invoice_id in (select invoice_id from invoices where case_id = any(v_case_ids));
  delete from invoices where case_id = any(v_case_ids);

  delete from meeting_participants where meeting_id in (select meeting_id from meetings where case_id = any(v_case_ids));
  delete from meetings where case_id = any(v_case_ids);
  delete from hearings where case_id = any(v_case_ids);

  delete from miscellaneous_expenses where matter_id = any(v_matter_ids);
  delete from property_registrations where matter_id = any(v_matter_ids);
  delete from registration_progress where matter_id = any(v_matter_ids);
  delete from due_diligence where matter_id = any(v_matter_ids);
  delete from conveyancing_parties where matter_id = any(v_matter_ids);
  delete from conveyancing_matters where matter_id = any(v_matter_ids);

  delete from case_ai_summaries where case_id = any(v_case_ids);
  delete from case_status_history where case_id = any(v_case_ids);
  delete from case_timeline where case_id = any(v_case_ids);
  delete from case_notes where case_id = any(v_case_ids);
  delete from case_lawyers where case_id = any(v_case_ids);
  delete from judgements where case_id = any(v_case_ids);
  delete from notifications where case_id = any(v_case_ids);
  delete from cases where case_id = any(v_case_ids);

  -- The person, and everything addressed to them rather than to a case.
  delete from messages where conversation_id = any(v_conv_ids) or sender_user_id = p_user_id;
  delete from conversations where id = any(v_conv_ids);
  delete from notifications where user_id = p_user_id;
  delete from meeting_participants where user_id = p_user_id;

  if v_lawyer_id is not null then
    delete from client_requests where lawyer_id = v_lawyer_id;
    delete from case_notes where lawyer_id = v_lawyer_id;
    delete from case_lawyers where lawyer_id = v_lawyer_id;
    update due_diligence set lawyer_id = null where lawyer_id = v_lawyer_id;
    delete from lawyers where lawyer_id = v_lawyer_id;
  end if;

  if v_client_id is not null then
    delete from client_requests where client_id = v_client_id;
    delete from clients where client_id = v_client_id;
  end if;

  -- Survivors keep the record, lose the name on it.
  update documents              set uploaded_by  = null where uploaded_by  = p_user_id;
  update case_timeline          set created_by   = null where created_by   = p_user_id;
  update case_status_history    set changed_by   = null where changed_by   = p_user_id;
  update meetings               set conducted_by = null where conducted_by = p_user_id;
  update matter_documents       set verified_by  = null where verified_by  = p_user_id;
  update miscellaneous_expenses set created_by   = null where created_by   = p_user_id;
  update judgements             set created_by   = null where created_by   = p_user_id;

  delete from users where user_id = p_user_id;

  return v_result || jsonb_build_object('dry_run', false);
end;
$$;
